{{- if .Values.autoscaler.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "openstack-cluster.componentName" (list . "autoscaler") }}
  labels: {{ include "openstack-cluster.componentLabels" (list . "autoscaler") | nindent 4 }}
rules:
  - apiGroups:
      - cluster.x-k8s.io
    resources:
      - machinedeployments
      - machinedeployments/scale
      - machines
      - machinesets
    verbs:
      - get
      - list
      - update
      - watch
{{- end }}
